<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Dell123" ignored="0" name="Command line test" tests="2" failures="1" timestamp="2022-05-21T13:16:29 IST" time="0.072" errors="0">
  <testcase name="testLogin1" time="0.016" classname="demo.AppTest"/>
  <testcase name="testLogin2" time="0.0" classname="demo.AppTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at demo.AppTest.testLogin2(AppTest.java:24)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 42 stack frames]]>
    </failure>
  </testcase> <!-- testLogin2 -->
</testsuite> <!-- Command line test -->
